#!/usr/bin/env bash
# =============================================================================
# StreamPack Desktop — setup script
#
# Run this ONCE after initialising the Flutter platform scaffolding:
#
#   cd desktop/streampack_flutter
#   flutter create --platforms=linux .
#   cd ..
#   bash setup.sh
#
# What this does:
#   1. Copies lib.streampack/ → lib/  (overwrites Flutter's generated main.dart
#      and any other placeholder files with StreamPack's actual source code)
#   2. Patches linux/CMakeLists.txt and windows/CMakeLists.txt to bundle
#      ffmpeg + ffprobe from vendor/ into the build output directory
#
# Safe to re-run — the CMake patch checks for its marker before modifying.
# The lib/ copy always overwrites (lib.streampack/ is the source of truth).
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLUTTER_DIR="$SCRIPT_DIR/streampack_flutter"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Validate ──────────────────────────────────────────────────────────────────
[[ -d "$FLUTTER_DIR/linux" ]] || \
    die "linux/ not found. Run 'flutter create --platforms=linux .' first."
[[ -d "$FLUTTER_DIR/lib.streampack" ]] || \
    die "lib.streampack/ not found — check you have the full StreamPack source."

# ── Step 1: Copy StreamPack lib sources into lib/ ─────────────────────────────
# lib.streampack/ is the source of truth. lib/ is owned by Flutter and will
# be regenerated by flutter create — we always overwrite it from lib.streampack/.
info "Copying lib.streampack/ → lib/ ..."
mkdir -p "$FLUTTER_DIR/lib/ui"
cp -r "$FLUTTER_DIR/lib.streampack/." "$FLUTTER_DIR/lib/"
success "lib/ updated from lib.streampack/"

# ── Step 1b: Revert any previous broken my_application.cc patches ────────────
MY_APP="$FLUTTER_DIR/linux/runner/my_application.cc"
if [[ -f "$MY_APP" ]] && grep -q "StreamPack" "$MY_APP"; then
    info "Reverting broken GTK patches from my_application.cc ..."
    PATCH_PY="$(mktemp /tmp/sp_revert_XXXXXX.py)"
    cat > "$PATCH_PY" << 'PYEOF'
import sys
path = sys.argv[1]
lines = open(path).read().split('\n')
bad = [
    'StreamPack', 'GdkRGBA', 'dark_bg', 'background_color',
    'gtk_widget_override', 'GtkCssProvider', 'gtk_css_provider',
    'gtk_style_context_add', 'g_object_unref', 'gtk_widget_realize',
    'gtk_events_pending', 'gtk_main_iteration',
]
clean = [l for l in lines if not any(b in l for b in bad)]
open(path, 'w').write('\n'.join(clean))
print('reverted')
PYEOF
    RESULT=$(python3 "$PATCH_PY" "$MY_APP")
    rm -f "$PATCH_PY"
    success "my_application.cc: $RESULT"
fi

# ── Step 1c: Install Linux window icon ────────────────────────────────────────
ASSETS_ICON="$FLUTTER_DIR/assets/icons/app_icon.png"
LINUX_ICON_DST="$FLUTTER_DIR/linux/runner/resources/my_app_icon.png"
MY_APP="$FLUTTER_DIR/linux/runner/my_application.cc"
if [[ -f "$ASSETS_ICON" ]] && [[ -d "$FLUTTER_DIR/linux" ]]; then
    mkdir -p "$(dirname "$LINUX_ICON_DST")"
    cp "$ASSETS_ICON" "$LINUX_ICON_DST"
    success "Linux icon installed to resources/"

    # Patch my_application.cc to load the icon if not already done
    if [[ -f "$MY_APP" ]] && ! grep -q "my_app_icon" "$MY_APP"; then
        python3 - "$MY_APP" << 'PYEOF'
import sys, re
path = sys.argv[1]
src  = open(path).read()
ins  = (
    '\n  // StreamPack: set window icon\n'
    '  GdkPixbuf* icon = gdk_pixbuf_new_from_file(\n'
    '      PACKAGE_DATA_DIR "/my_app_icon.png", nullptr);\n'
    '  if (icon) {\n'
    '    gtk_window_set_icon(window, icon);\n'
    '    g_object_unref(icon);\n'
    '  }\n'
)
out = re.sub(
    r'(gtk_widget_show(?:_all)?\s*\([^)]+\)\s*;)',
    r'\1' + ins, src, count=1
)
open(path, 'w').write(out)
PYEOF
        success "my_application.cc patched for icon"
    fi
fi

# ── Step 2: Patch CMakeLists.txt files to bundle ffmpeg ───────────────────────
LINUX_CMAKE="$FLUTTER_DIR/linux/CMakeLists.txt"
WIN_CMAKE="$FLUTTER_DIR/windows/CMakeLists.txt"
MARKER="# StreamPack: bundle ffmpeg"

# Linux
if grep -q "$MARKER" "$LINUX_CMAKE" 2>/dev/null; then
    warn "linux/CMakeLists.txt already patched — skipping"
else
    info "Patching linux/CMakeLists.txt ..."
    cat >> "$LINUX_CMAKE" << 'EOF'

# StreamPack: bundle ffmpeg + ffprobe into the output directory ────────────────
# Vendor binaries are built by: cd desktop && bash build-ffmpeg.sh linux
set(STREAMPACK_VENDOR_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../vendor/linux")

if(EXISTS "${STREAMPACK_VENDOR_DIR}/ffmpeg" AND
   EXISTS "${STREAMPACK_VENDOR_DIR}/ffprobe")
  message(STATUS "StreamPack: bundling ffmpeg from ${STREAMPACK_VENDOR_DIR}")
  install(PROGRAMS
    "${STREAMPACK_VENDOR_DIR}/ffmpeg"
    "${STREAMPACK_VENDOR_DIR}/ffprobe"
    DESTINATION "${CMAKE_INSTALL_PREFIX}"
  )
else()
  message(WARNING
    "StreamPack: ffmpeg not found in ${STREAMPACK_VENDOR_DIR} — "
    "app will require system ffmpeg. Run 'bash build-ffmpeg.sh linux' first.")
endif()

# StreamPack: install app icon
install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/runner/resources/my_app_icon.png"
        DESTINATION "${CMAKE_INSTALL_PREFIX}")
# ─────────────────────────────────────────────────────────────────────────────
EOF
    success "linux/CMakeLists.txt patched"
fi

# Windows (optional — only patch if windows/ was created by flutter create)
if [[ -d "$FLUTTER_DIR/windows" ]]; then
    if grep -q "$MARKER" "$WIN_CMAKE" 2>/dev/null; then
        warn "windows/CMakeLists.txt already patched — skipping"
    else
        info "Patching windows/CMakeLists.txt ..."
        cat >> "$WIN_CMAKE" << 'EOF'

# StreamPack: bundle ffmpeg + ffprobe into the output directory
# Vendor binaries are built by: cd desktop && bash build-ffmpeg.sh windows
set(STREAMPACK_VENDOR_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../vendor/windows")

if(EXISTS "${STREAMPACK_VENDOR_DIR}/ffmpeg.exe" AND
   EXISTS "${STREAMPACK_VENDOR_DIR}/ffprobe.exe")
  message(STATUS "StreamPack: bundling ffmpeg from ${STREAMPACK_VENDOR_DIR}")
  install(PROGRAMS
    "${STREAMPACK_VENDOR_DIR}/ffmpeg.exe"
    "${STREAMPACK_VENDOR_DIR}/ffprobe.exe"
    DESTINATION "${CMAKE_INSTALL_PREFIX}"
  )
else()
  message(WARNING
    "StreamPack: ffmpeg.exe not found in ${STREAMPACK_VENDOR_DIR} -- "
    "app will require system ffmpeg. Copy cross-compiled binaries to "
    "desktop/vendor/windows/ first.")
endif()
EOF
        success "windows/CMakeLists.txt patched"
    fi
else
    info "windows/ not present — skipping Windows CMake patch (Linux-only build)"
fi

echo
echo -e "${GREEN}Setup complete.${NC} Now build:"
echo -e "  ${CYAN}cd streampack_flutter && flutter pub get && flutter build linux --release${NC}"
echo
echo -e "If you re-run 'flutter create' in future, re-run this script afterwards"
echo -e "to restore lib/ from lib.streampack/."
